import React from 'react'

const About = () => {
  return (
    <div>In 1985, Balkrishan Goenka, along with his cousin Rajesh R Mandawewala, founded Welspun with an initial investment of $100,000 borrowed from his father.[3] The company began its operations as a small texturizing unit under the name Welspun Winilon Silk Mills in the Palghar district.[4] It was promoted by the G.R.G. group, headed by Gopi Ram Goenka, who is the father of Balkrishan.[1][5][3]

Between 1986 and 1989, the company established two yarn texturizing factories.[6] One, situated in Palghar, produced 797.5 MT of yarn annually. The second factory, with a similar capacity, was set up in Silvassa. In 1990, the company expanded its operations by establishing a polyester filament flat yarn manufacturing unit in Thane, with a capacity of 605 MT per annum. The company's name was later changed to Welspun Polyester India Limited.[6]

In 1991, Welspun Polyester India went public through its initial public offering (IPO) and later rebranded as Welspun India Limited (WIL).[1] The company expanded into the terry towels business by setting up its first terry towel plant in Vapi, Gujarat, with 15,000 cotton spindles.[6][3] Welspun also proposed a POY project in Silvassa, Dadra, and Nagar Haveli, with a capacity of 15,000 metric tonnes per annum (MTPA). Between 1994 and 1995, the company increased its terry towel production capacity from 3100 MTPA to 5200 MTPA. Additionally, it started developing power plants capable of generating 40 M.W., intended to support spinning machines for terry towels and cotton through captive power sources. Welspun also acquired a plant from Rieter Automatic Gmbh in Germany to launch its polyester filament yarn project.[7] In 1996, Welspun's polyester yarn business was leased to a group company to shift focus to natural fibers.[6] In 1999, Welspun entered a joint venture with Vincenzo Zucchi SPA, Italy, for Terry Bathrobes and Terry made-ups production at its Vapi, Gujarat plant.[8] In 2000, Welspun USA was formed as a wholly-owned subsidiary of Welspun India Limited.[9]

In 2001, Welspun hived off its cotton yarn unit into a separate company, which became known as Welspun Cotton Yarn Ltd.[6][10] CRISIL, an analytical company in India, subsequently downgraded the company's NCDs from a "B" rating to a "D" rating. In 2004, Welspun India received Walmart's Supplier of the Year for Bed & Bath.[11] In 2009, Welspun appointed B K Goenka as the Chairman and Managing Director.[12] In 2013, Welspun Corp. Ltd., a subsidiary of Welspun Group, divested its entire 39.88 percent stake in Leighton Welspun India for USD 99 million.[13]

In 2015 and 2016, Welspun was granted the contract for Package I development of Delhi–Meerut Expressway, covering 8.7 km in Delhi, with a total estimated project cost of ₹841.50 crore (US$110 million).[14][15] The expressway segment was officially inaugurated on May 27, 2018, by Prime Minister Narendra Modi.[16] During the same period, Welspun initiated a 32 MW solar power plant,[17] launched an online retail portal,[18] and expanded into flooring solutions with a ₹600 crore carpet plant in Anjar, Gujarat.[19] The group also closed one of its plants in Mexico.[20]

In December 2019, the group entered the warehousing sector through the acquisition of majority stakes in One Industrial Spaces.[21] In 2020, Welspun Flooring Ltd, a subsidiary of Welspun Group, established a manufacturing facility in Hyderabad with an annual capacity of 40 million square meters.[22] In February 2023, the Welspun Group launched a textile facility in Telangana, inaugurated by IT and Industries Minister KT Rama Rao. During the event, the group disclosed its intentions to establish IT centers in Chandanvelly, Ranga Reddy district in Telangana.[23] Also, the Welspun Group announced a Rs 2,000 crore investment for the development of an integrated textile manufacturing zone in Kutch, Gujarat, in alignment with the Indian government's Sagar Mala project. This initiative was aimed at facilitating the global manufacturing and supply of textile products.[24]

In March 2023, the group expanded its presence in the building materials sector by acquiring Sintex BAPL, a water tank manufacturer, for Rs 1,251 crore through its subsidiary, Welspun Corporation.[25] During FY19, Sintex had reported an operating profit of Rs 270 crore on a turnover of Rs 1,800 crore. However, the company faced financial difficulties and was taken to the bankruptcy court in December 2020 due to default on loan repayments.[26] In February 2023, The National Company Law Tribunal (NCLT) admitted the insolvency plea against Sintex, but it was later dismissed by NCLAT.[27] In July 2023, the group re-branded itself as Welspun World.</div>
  )
}

export default About